/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykhachsan.Form;

import DAO.PhongDAo;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.HEIGHT;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Phong;


/**
 *
 * @author NHS
 */
public class managerQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form managerQuanLy
     */
    private PhongDAo quanly;
    private List<Phong> listsv;

    public managerQuanLy() {
        initComponents();
        quanly = new PhongDAo();
        loadTable();
        txtDateNow.setEditable(false);
        LayGioHeThong();
        listsv = quanly.getlist();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btDatPhong = new javax.swing.JButton();
        butTraPhong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePhong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDateNow = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHoTEN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        txtTraPhong = new javax.swing.JTextField();
        cbTinhTrang = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoPhong = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btDatPhong.setText("Đặt Phòng");
        btDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDatPhongActionPerformed(evt);
            }
        });

        butTraPhong.setText("Trả Phòng");
        butTraPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTraPhongActionPerformed(evt);
            }
        });

        TablePhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePhong);

        jLabel1.setText("Ngày Hôm Nay");

        jLabel2.setText("Họ Tên KH");

        jLabel3.setText("CMND");

        cbTinhTrang.setText("TinhTrang");

        jLabel4.setText("Ngày Trả Phòng");

        jLabel5.setText("Mã Phòng");

        jLabel7.setText("Số Phòng");

        jButton2.setText("Thanh Toán");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Quản lý Nhân Viên");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Quản lý Dịch Vụ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDatPhong)
                            .addComponent(jButton2)
                            .addComponent(butTraPhong))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDateNow)
                            .addComponent(txtHoTEN)
                            .addComponent(txtCMND, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(txtSoPhong))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTinhTrang)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTraPhong)
                                    .addComponent(txtMaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDatPhong)
                            .addComponent(jLabel1)
                            .addComponent(txtDateNow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHoTEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(butTraPhong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTinhTrang)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePhongMouseClicked
        int index = TablePhong.getSelectedRow();
        DateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (index >= 0) {

            //Kiểm Tra người dùng có bấm hay không ( nếu thì set )
            Date date1 = listsv.get(index).getNgayTra();
            Date date2 = listsv.get(index).getNgayVao();
            
            txtHoTEN.setText(listsv.get(index).getTenKh());
            txtCMND.setText(listsv.get(index).getCMND());
            txtMaPhong.setText(listsv.get(index).getMaPhong());
            txtSoPhong.setText(String.valueOf(listsv.get(index).getSoPhong()));
//            txtTraPhong.setText(simpleDateFormat.format(date1));
//            txtDateNow.setText(simpleDateFormat.format(date2));
            System.out.println(date2);
            if (listsv.get(index).isTinhTrang()) {
                cbTinhTrang.setSelected(true);
            } else {
                cbTinhTrang.setSelected(false);
            }
        }
    }//GEN-LAST:event_TablePhongMouseClicked

    private void butTraPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTraPhongActionPerformed
        DateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        StringBuilder sb = new StringBuilder();
        Date date1 = null;
        Date date2 = null;
        String NgayTra = txtTraPhong.getText();
        String NgayVao = txtDateNow.getText();
        int SoPhong = 0;
        try {
            date1 = simpleDateFormat.parse(NgayTra);

        } catch (ParseException ex) {

            sb.append("\"Không đúng định dạng yyyy-MM-dd \"");
        }

        try {
            SoPhong = Integer.parseInt(txtSoPhong.getText());
        } catch (Exception ex) {
            sb.append("Để Không đúng định dạng , phải là Số\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông Báo", HEIGHT);
        } else {
            for (Phong phong : listsv) {
                if (phong.getSoPhong() == SoPhong) {
                    phong.setNgayTra(date1);
                    quanly.TraPhong(phong);
                }
            }
            loadTable();
        }


    }//GEN-LAST:event_butTraPhongActionPerformed

    private void btDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDatPhongActionPerformed
        DateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        StringBuilder sb = new StringBuilder();
        Date date1 = null;
        String startDate = txtDateNow.getText();
        try {
            date1 = simpleDateFormat.parse(startDate);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Không đúng định dạng yyyy-MM-dd ", "Thông Báo", HEIGHT);
        }
        String TenKh = txtHoTEN.getText();
        String CMND = txtCMND.getText();
        String MaPhong = txtMaPhong.getText();
        int SoPhong = 0;
        float GiaPhong = 0;

        boolean TinhTrang = false;
        try {
            SoPhong = Integer.parseInt(txtSoPhong.getText());
        } catch (Exception ex) {
            sb.append("Để Không đúng định dạng , phải là Số\n");
        }
        if (txtHoTEN.getText().equals("")) {
            sb.append("Không Để Trống HoTen \n");
        }
        if (txtCMND.getText().equals("")) {
            sb.append("Không Để Trống CMND \n");

        }
        if (txtMaPhong.getText().equals("")) {
            sb.append("Không Để Trống MaPhong \n");

        }
        if (txtSoPhong.getText().equals("")) {
            sb.append("Không Để Trống SoPhong \n");

        }
        if (!cbTinhTrang.isSelected()) {
            sb.append("Không Để Trống Tinh Trang \n");
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông Báo", HEIGHT);
        } else {

            if (cbTinhTrang.isSelected()) {
                TinhTrang = true;
            }

            PhongDAo a = new PhongDAo();
            Phong b = new Phong(MaPhong, SoPhong, date1, TenKh, CMND, TinhTrang);
            System.out.println(b.toString());
            a.DatPhong(b);
            loadTable();
        }
    }//GEN-LAST:event_btDatPhongActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StringBuilder sb = new StringBuilder();
         int index = TablePhong.getSelectedRow();
        if (index >= 0) {
             sb.append("Số Tiền Cần Thanh Toán :" + listsv.get(index).TinhTongTien());
          if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông Báo", HEIGHT);
            quanly.XoaPhong(listsv.get(index).getSoPhong());
            loadTable();
          }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                this.setVisible(false);
                Manager Menu = new Manager();
                Menu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                this.setVisible(false);
                DichVU Menu = new DichVU();
                Menu.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

   
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(managerQuanLy.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(managerQuanLy.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(managerQuanLy.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(managerQuanLy.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new managerQuanLy().setVisible(true);
//            }
//        });
//    }

    public void loadTable() {
        String[] b = new String[]{"MaPhong ", "So Phong", ",Gia Phong ", "TenKh", "CMND", "NgayVao", "NgayTra", "TongTien", "TinhTrang"};
        DefaultTableModel a = new DefaultTableModel(b, 0);

        List<Phong> listsv = new ArrayList<>();
        PhongDAo quan = new PhongDAo();
        String TinhTrang = null;
        a.setNumRows(0);
        long tongtien = 0;
        listsv = quan.getlist();
        for (Phong c : listsv) {
            if (c.isTinhTrang()) {
                TinhTrang = "Đang Sử Dụng";
            }
            
            if (c.TinhTongTien() != 0) {
                tongtien = c.TinhTongTien();
                c.setTongTien((long)tongtien);
            } else {
                tongtien = 0;
            }
            
            a.addRow(new Object[]{c.getMaPhong(), c.getSoPhong(), c.getGiaPhong(),
                c.getTenKh(), c.getCMND(), c.getNgayVao(), c.getNgayTra(),tongtien, TinhTrang});
        }
        TablePhong.setModel(a);
    }

    public void LayGioHeThong() {
        DateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        txtDateNow.setText(java.time.LocalDate.now().toString());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePhong;
    private javax.swing.JButton btDatPhong;
    private javax.swing.JButton butTraPhong;
    private javax.swing.JCheckBox cbTinhTrang;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDateNow;
    private javax.swing.JTextField txtHoTEN;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtSoPhong;
    private javax.swing.JTextField txtTraPhong;
    // End of variables declaration//GEN-END:variables
}
